Loops (while and for)

```{r}

# loop example
#for (item in list){
#  do something with that item
#}
```

```{r}
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
for (day in weekdays) {
  phrase <- paste("The day is", day)
print(phrase)
}

# day is often called as loop variable 
```

```{r}
x <- 1:5
for (ii in x) {
 print(ii)
}
```


```{r}
x <- 1:5
for (ii in x) {
 print(paste0("print(", ii, ")"))
}
```

```{r}
numbers <-7:11
for (position in 1:length(numbers)){
  number <- numbers[position]
  print(number)
}
```

```{r}
current_value <-1
stop_value <- 10

while (current_value < stop_value){
  print(current_value)
  current_value <- current_value +1
}
```

```{r}
# We add the letter s to our vector

weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
plurals <- c()

for (day in weekdays){
  plural <- paste0(day, "s")
  plurals <- c(plurals, plural)
}
plurals
```

```{r}
# We add the letter s to our vector

weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
plurals <- rep("", length(weekdays))

for (position in 1:length(weekdays)){
  this_plural <- paste0(weekdays[position], "s")
  plurals[position] <- this_plural
}
plurals
```


```{r}
my_matrix <- replicate(5, rnorm(5))
my_matrix

#Number of rows
num_rows <- dim(my_matrix)[1]
num_rows

#Number of columns
num_cols <- dim(my_matrix)[2]
num_cols

for (row_index in 1:num_rows){
  for (col_index in 1:num_cols){
    print(my_matrix[row_index, col_index])
  }
}

```

```{r}
# We now if statement inside a nested loop
my_matrix <- replicate(5, rnorm(5))
my_matrix

#Number of rows
num_rows <- dim(my_matrix)[1]
num_rows

#Number of columns
num_cols <- dim(my_matrix)[2]
num_cols

for (row_index in 1:num_rows){
  for (col_index in 1:num_cols){
    if (row_index == col_index){
        print(my_matrix[row_index, col_index])
    }
  }
}
```


```{r}
# "apply" functions
m1 <- matrix(data = 1:10, nrow = 5, ncol = 6)
m1

sum_cols_m1 <- apply (X = m1, MARGIN =2, FUN =sum)
sum_cols_m1



```



```{r}
#x <- 1:6
#a <- x[1:end]
#a
```

